title: <p align="center"> Darel Lasrado </p>
logo: /assets/img/darel.jpeg

description:
  <p align="center">
  <a href="docs/Resume%20-%20Darel%20Lasrado.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/darellasrado/">LinkedIn</a> |
  <a href="https://github.com/lasrado">GitHub</a>
 
  <br>  
  I'm working on Data Science, Big Data,Machine learning & AI related problems.
  
  <br>
  </p>


show_downloads: false
theme: jekyll-theme-minimal
